### ISSUE TITLE
Collisions between `EIP712Type` dataclass properties and struct field names

### ISSUE THREAD

**Issue by skellet0r** [ApeWorX/eip712#16]
### What went wrong?

Creating an `EIP712Message` subclass with field names that conflict with method and property names causes encoding errors.

For example the following struct definition 
```python
from eip712.messages import EIP712Message
from dataclassy import as_dict

class Transaction(EIP712Message):
    _name_: "string" = "zkSync"
    _version_: "string" = "2"
    _chainId_: "uint256"

    txType: "uint8"
    to: "uint256"
    value: "uint256"
    data: "bytes"
    feeToken: "uint256"
    ergsLimit: "uint256"
    ergsPerPubdataByteLimit: "uint256"
    ergsPrice: "uint256"
    nonce: "uint256"

tx_struct = Transaction(280, 0x71, 0, 0, b"", 0, 0, 0, 0, 0)

# https://github.com/ApeWorX/eip712/blob/main/eip712/messages.py#L113
assert {k: v for k, v in as_dict(tx).items() if not k.startswith("_")} == tx.data
```

The above fails because the [`data`](https://github.com/ApeWorX/eip712/blob/main/eip712/messages.py#L113) method is overwritten by the data field defined in the subclass.

## Potential solutions

- Make all properties and methods private

**Comment by skellet0r** [comment]
Related #9

**Comment by fubuloubu** [comment]
Closed as duplicate (but thanks for additional test case)
