### ISSUE TITLE
cant work with package: web3 

### ISSUE THREAD

**Issue by lijiachang** [ApeWorX/eip712#30]
### Overview

-- python: 3.8.10
-- eip712: 0.1.6
-- web3: 5.31.3 (lastest)

when i install eip712 & web3:
**The conflict is caused by:
    eip712 0.1.6 depends on eth-typing<4 and >=3.2
    web3 5.31.3 depends on eth-typing<3.0.0 and >=2.0.0**

https://github.com/ethereum/web3.py
web3  is popular，can we work with them？

**Comment by lijiachang** [comment]
> 
eth-typing==2.3.0

I tested without any issues

**Comment by fubuloubu** [comment]
Released with https://github.com/ApeWorX/eip712/releases/tag/v0.1.7
