### ISSUE TITLE
`sphinx-autogen` ...no module named errors

### ISSUE THREAD

**Issue by robrobbins** [ApeWorX/eip712#8]
![image](https://user-images.githubusercontent.com/60326/137928880-0d1148cb-7bf8-4e19-8f3b-75eacbcf997a.png)

tried from root and /docs

**Comment by fubuloubu** [comment]
@robrobbins can you share how you arrived at this error?

**Comment by fubuloubu** [comment]
Can't reproduce this issue, so closing for now
